import React, { useState } from 'react';
import enhancedAIService from '../services/enhancedAIService';

const StudyPlanner = () => {
  const [subject, setSubject] = useState('');
  const [duration, setDuration] = useState('4 weeks');
  const [level, setLevel] = useState('beginner');
  const [goals, setGoals] = useState('');
  const [studyPlan, setStudyPlan] = useState(null);
  const [loading, setLoading] = useState(false);

  const generatePlan = async () => {
    if (!subject || !goals) {
      alert('Please fill in subject and goals!');
      return;
    }
    setLoading(true);
    try {
      const plan = await enhancedAIService.createStudyPlan(subject, duration, level, goals);
      setStudyPlan(plan);
    } catch (error) {
      console.error('Error generating study plan:', error);
      alert('Failed to generate study plan. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const exportPlan = () => {
    if (!studyPlan) return;
    const planText = `
MY STUDY PLAN
=============
Subject: ${studyPlan.subject}
Duration: ${studyPlan.duration}
Level: ${studyPlan.level}

${studyPlan.plan}

Generated by AI Learning Tutor
${new Date().toLocaleDateString()}
    `;
    const blob = new Blob([planText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Study-Plan-${studyPlan.subject.replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="card text-center py-16">
        <div className="animate-spin text-6xl mb-4">📅</div>
        <p className="text-xl text-white/70">Creating your personalized study plan...</p>
      </div>
    );
  }

  if (!studyPlan) {
    return (
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="card">
          <div className="text-center mb-8">
            <h2 className="text-4xl font-bold gradient-text mb-3 flex items-center justify-center gap-3">
              <span>📅</span> Create Your Study Plan
            </h2>
            <p className="text-white/70 text-lg">Get a personalized, structured plan to master any subject</p>
          </div>

          <div className="space-y-6">
            <div>
              <label className="block text-white font-semibold mb-2">What do you want to learn?</label>
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                placeholder="e.g., Web Development, Data Science, Spanish"
                className="input-field"
              />
            </div>

            <div>
              <label className="block text-white font-semibold mb-2">How much time do you have?</label>
              <select value={duration} onChange={(e) => setDuration(e.target.value)} className="input-field cursor-pointer">
                <option value="2 weeks">2 Weeks (Crash Course)</option>
                <option value="4 weeks">4 Weeks (Standard)</option>
                <option value="8 weeks">8 Weeks (Comprehensive)</option>
                <option value="12 weeks">12 Weeks (In-Depth)</option>
                <option value="6 months">6 Months (Mastery)</option>
              </select>
            </div>

            <div>
              <label className="block text-white font-semibold mb-3">Current Level:</label>
              <div className="grid grid-cols-3 gap-3">
                <button
                  onClick={() => setLevel('beginner')}
                  type="button"
                  className={`py-3 px-4 rounded-xl font-semibold transition-all ${
                    level === 'beginner' ? 'bg-gradient-to-r from-blue-500 to-purple-600 shadow-lg' : 'glass hover:bg-white/20'
                  }`}
                >
                  🌱 Beginner
                </button>
                <button
                  onClick={() => setLevel('intermediate')}
                  type="button"
                  className={`py-3 px-4 rounded-xl font-semibold transition-all ${
                    level === 'intermediate' ? 'bg-gradient-to-r from-blue-500 to-purple-600 shadow-lg' : 'glass hover:bg-white/20'
                  }`}
                >
                  📚 Intermediate
                </button>
                <button
                  onClick={() => setLevel('advanced')}
                  type="button"
                  className={`py-3 px-4 rounded-xl font-semibold transition-all ${
                    level === 'advanced' ? 'bg-gradient-to-r from-blue-500 to-purple-600 shadow-lg' : 'glass hover:bg-white/20'
                  }`}
                >
                  ⭐ Advanced
                </button>
              </div>
            </div>

            <div>
              <label className="block text-white font-semibold mb-2">What are your learning goals?</label>
              <textarea
                value={goals}
                onChange={(e) => setGoals(e.target.value)}
                placeholder="e.g., Build a portfolio website, Get job-ready, Pass certification exam..."
                rows="4"
                className="input-field resize-none"
              />
            </div>

            <button className="btn-primary w-full text-lg py-4" onClick={generatePlan} type="button">
              Generate My Study Plan 🎯
            </button>
          </div>
        </div>

        <div className="card">
          <h3 className="text-2xl font-bold gradient-text mb-6 text-center">✨ Your Plan Includes:</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="glass p-6 rounded-xl text-center hover:bg-white/20 transition-all">
              <div className="text-4xl mb-3">📆</div>
              <p className="font-semibold text-sm">Week-by-week breakdown</p>
            </div>
            <div className="glass p-6 rounded-xl text-center hover:bg-white/20 transition-all">
              <div className="text-4xl mb-3">⏰</div>
              <p className="font-semibold text-sm">Daily time allocation</p>
            </div>
            <div className="glass p-6 rounded-xl text-center hover:bg-white/20 transition-all">
              <div className="text-4xl mb-3">📚</div>
              <p className="font-semibold text-sm">Specific topics</p>
            </div>
            <div className="glass p-6 rounded-xl text-center hover:bg-white/20 transition-all">
              <div className="text-4xl mb-3">🎯</div>
              <p className="font-semibold text-sm">Milestones</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="card">
        <h2 className="text-3xl font-bold gradient-text mb-4 flex items-center gap-2">
          <span>📚</span> Your Personalized Study Plan
        </h2>
        <div className="flex flex-wrap gap-3 mb-6">
          <span className="glass px-4 py-2 rounded-full text-sm flex items-center gap-2">
            <span>📖</span> {studyPlan.subject}
          </span>
          <span className="glass px-4 py-2 rounded-full text-sm flex items-center gap-2">
            <span>⏱️</span> {studyPlan.duration}
          </span>
          <span className="glass px-4 py-2 rounded-full text-sm flex items-center gap-2">
            <span>📊</span> {studyPlan.level}
          </span>
        </div>
      </div>

      <div className="space-y-4">
        {studyPlan.plan.split('\n\n').filter(section => section.trim()).map((section, index) => {
          const lines = section.split('\n');
          const title = lines[0].replace(/\*\*/g, '').trim();
          const content = lines.slice(1).join('\n');
          
          return (
            <div key={index} className="card">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-2xl font-bold gradient-text">{title}</h3>
                <span className="glass px-3 py-1 rounded-full text-sm font-semibold">Week {index + 1}</span>
              </div>
              <div className="space-y-2 text-white/80">
                {content.split('\n').map((line, i) => {
                  if (line.trim().startsWith('•') || line.trim().startsWith('✓') || line.trim().startsWith('→')) {
                    return <p key={i} className="ml-4">• {line.substring(1).trim()}</p>;
                  } else if (line.trim()) {
                    return <p key={i}>{line}</p>;
                  }
                  return null;
                })}
              </div>
            </div>
          );
        })}
      </div>

      <div className="flex gap-4">
        <button 
          className="btn-secondary flex-1"
          onClick={() => setStudyPlan(null)}
          type="button"
        >
          📝 Create New Plan
        </button>
        <button 
          className="btn-primary flex-1"
          onClick={exportPlan}
          type="button"
        >
          📥 Export Plan
        </button>
      </div>

      <div className="card border-green-500/50">
        <h3 className="text-2xl font-bold gradient-text mb-4 flex items-center gap-2">
          <span>💡</span> Tips for Success
        </h3>
        <div className="space-y-3">
          <div className="glass p-4 rounded-xl border-l-4 border-green-500">
            <p className="text-white/80">✅ Stick to the schedule - consistency is key</p>
          </div>
          <div className="glass p-4 rounded-xl border-l-4 border-green-500">
            <p className="text-white/80">✅ Don't skip fundamentals - they're crucial</p>
          </div>
          <div className="glass p-4 rounded-xl border-l-4 border-green-500">
            <p className="text-white/80">✅ Practice daily, even if just for 20 minutes</p>
          </div>
          <div className="glass p-4 rounded-xl border-l-4 border-green-500">
            <p className="text-white/80">✅ Track your progress and adjust as needed</p>
          </div>
          <div className="glass p-4 rounded-xl border-l-4 border-green-500">
            <p className="text-white/80">✅ Join communities for support and motivation</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default StudyPlanner;
