import React, { useState } from 'react';
import enhancedAIService from '../services/enhancedAIService';
const StudyPlanner = () => {
  const [subject, setSubject] = useState('');
  const [duration, setDuration] = useState('4 weeks');
  const [level, setLevel] = useState('beginner');
  const [goals, setGoals] = useState('');
  const [studyPlan, setStudyPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const generatePlan = async () => {
    if (!subject || !goals) {
      alert('Please fill in subject and goals!');
      return;
    }
    setLoading(true);
    try {
      const plan = await enhancedAIService.createStudyPlan(subject, duration, level, goals);
      setStudyPlan(plan);
    } catch (error) {
      console.error('Error generating study plan:', error);
      alert('Failed to generate study plan. Please try again.');
    } finally {
      setLoading(false);
    }
  };
  const exportPlan = () => {
    if (!studyPlan) return;
    const planText = `
MY STUDY PLAN
=============
Subject: ${studyPlan.subject}
Duration: ${studyPlan.duration}
Level: ${studyPlan.level}
${studyPlan.plan}
Generated by AI Learning Tutor
${new Date().toLocaleDateString()}
    `;
    const blob = new Blob([planText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Study-Plan-${studyPlan.subject.replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };
  if (loading) {
    return (
      <div className="card text-center py-16">
        <div className="animate-spin text-6xl mb-4">📚</div>
        <p className="text-lg" style={{color: 'rgba(232, 234, 246, 0.8)'}}>Creating your personalized study plan...</p>
      </div>
    );
  }
  if (!studyPlan) {
    return (
      <div className="max-w-4xl mx-auto">
        <div className="card">
          <h2 className="text-2xl font-bold mb-2" style={{color: '#7c8ef5'}}>📅 Create Your Study Plan</h2>
          <p className="mb-6" style={{color: 'rgba(232, 234, 246, 0.7)'}}>Get a personalized, structured plan to master any subject</p>
          
          <div className="space-y-5">
            <div>
              <label className="block text-sm font-semibold mb-2" style={{color: '#e8eaf6'}}>What do you want to learn?</label>
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                placeholder="e.g., Web Development, Data Science, Spanish"
                className="input-field w-full"
              />
            </div>
            
            <div>
              <label className="block text-sm font-semibold mb-2" style={{color: '#e8eaf6'}}>How much time do you have?</label>
              <select value={duration} onChange={(e) => setDuration(e.target.value)} className="input-field w-full cursor-pointer">
                <option value="2 weeks">2 Weeks (Crash Course)</option>
                <option value="4 weeks">4 Weeks (Standard)</option>
                <option value="8 weeks">8 Weeks (Comprehensive)</option>
                <option value="12 weeks">12 Weeks (In-Depth)</option>
                <option value="6 months">6 Months (Mastery)</option>
              </select>
            </div>
            
            <div>
              <label className="block text-sm font-semibold mb-2" style={{color: '#e8eaf6'}}>Current Level</label>
              <div className="grid grid-cols-3 gap-3">
                <button
                  className={`py-3 rounded-lg border transition-all ${level === 'beginner' ? 'bg-blue-500/20 border-blue-500/50' : 'border-gray-600 hover:border-gray-500'}`}
                  onClick={() => setLevel('beginner')}
                  type="button"
                >
                  <div className="text-2xl mb-1">🌱</div>
                  <div className="text-sm">Beginner</div>
                </button>
                <button
                  className={`py-3 rounded-lg border transition-all ${level === 'intermediate' ? 'bg-blue-500/20 border-blue-500/50' : 'border-gray-600 hover:border-gray-500'}`}
                  onClick={() => setLevel('intermediate')}
                  type="button"
                >
                  <div className="text-2xl mb-1">📚</div>
                  <div className="text-sm">Intermediate</div>
                </button>
                <button
                  className={`py-3 rounded-lg border transition-all ${level === 'advanced' ? 'bg-blue-500/20 border-blue-500/50' : 'border-gray-600 hover:border-gray-500'}`}
                  onClick={() => setLevel('advanced')}
                  type="button"
                >
                  <div className="text-2xl mb-1">⭐</div>
                  <div className="text-sm">Advanced</div>
                </button>
              </div>
            </div>
            
            <div>
              <label className="block text-sm font-semibold mb-2" style={{color: '#e8eaf6'}}>What are your learning goals?</label>
              <textarea
                value={goals}
                onChange={(e) => setGoals(e.target.value)}
                placeholder="e.g., Build a portfolio website, Get job-ready, Pass certification exam..."
                rows="4"
                className="input-field w-full resize-none"
              />
            </div>
            
            <button className="btn-primary w-full py-3" onClick={generatePlan} type="button">
              🎯 Generate My Study Plan
            </button>
          </div>
        </div>
        
        <div className="card mt-5" style={{borderColor: 'rgba(91, 110, 225, 0.3)'}}>
          <h3 className="text-lg font-semibold mb-4 text-center" style={{color: '#7c8ef5'}}>✨ Your Plan Includes</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div className="text-center p-3 glass rounded-lg">
              <div className="text-3xl mb-2">📆</div>
              <p className="text-xs" style={{color: 'rgba(232, 234, 246, 0.8)'}}>Week-by-week breakdown</p>
            </div>
            <div className="text-center p-3 glass rounded-lg">
              <div className="text-3xl mb-2">⏰</div>
              <p className="text-xs" style={{color: 'rgba(232, 234, 246, 0.8)'}}>Daily time allocation</p>
            </div>
            <div className="text-center p-3 glass rounded-lg">
              <div className="text-3xl mb-2">📚</div>
              <p className="text-xs" style={{color: 'rgba(232, 234, 246, 0.8)'}}>Specific topics</p>
            </div>
            <div className="text-center p-3 glass rounded-lg">
              <div className="text-3xl mb-2">🎯</div>
              <p className="text-xs" style={{color: 'rgba(232, 234, 246, 0.8)'}}>Milestones</p>
            </div>
          </div>
        </div>
      </div>
    );
  }
  return (
    <div className="max-w-5xl mx-auto">
      <div className="card mb-4">
        <h2 className="text-2xl font-bold mb-3" style={{color: '#7c8ef5'}}>📚 Your Personalized Study Plan</h2>
        <div className="flex flex-wrap gap-3">
          <span className="glass px-3 py-1 rounded text-sm">📖 {studyPlan.subject}</span>
          <span className="glass px-3 py-1 rounded text-sm">⏱️ {studyPlan.duration}</span>
          <span className="glass px-3 py-1 rounded text-sm">📊 {studyPlan.level}</span>
        </div>
      </div>
      
      <div className="space-y-4">
        {studyPlan.plan.split('\n\n').filter(section => section.trim()).map((section, index) => {
          const lines = section.split('\n');
          const title = lines[0].replace(/\*\*/g, '').trim();
          const content = lines.slice(1).join('\n');
          return (
            <div key={index} className="card">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-lg font-semibold" style={{color: '#7c8ef5'}}>{title}</h3>
                <span className="glass px-3 py-1 rounded text-xs">Week {index + 1}</span>
              </div>
              <div className="space-y-2 text-sm" style={{color: 'rgba(232, 234, 246, 0.8)'}}>
                {content.split('\n').map((line, i) => {
                  if (line.trim().startsWith('•') || line.trim().startsWith('✓') || line.trim().startsWith('→')) {
                    return <p key={i} className="ml-4">• {line.substring(1).trim()}</p>;
                  } else if (line.trim()) {
                    return <p key={i}>{line}</p>;
                  }
                  return null;
                })}
              </div>
            </div>
          );
        })}
      </div>
      
      <div className="flex gap-3 mt-5">
        <button 
          className="btn-secondary flex-1"
          onClick={() => setStudyPlan(null)}
          type="button"
        >
          📝 Create New Plan
        </button>
        <button 
          className="btn-primary flex-1"
          onClick={exportPlan}
          type="button"
        >
          📥 Export Plan
        </button>
      </div>
      
      <div className="card mt-5" style={{borderColor: 'rgba(34, 197, 94, 0.3)'}}>
        <h3 className="text-lg font-semibold mb-3" style={{color: '#22c55e'}}>💡 Tips for Success</h3>
        <div className="space-y-2">
          <div className="glass p-3 rounded text-sm" style={{borderLeft: '3px solid #22c55e', color: 'rgba(232, 234, 246, 0.8)'}}>
            ✅ Stick to the schedule - consistency is key
          </div>
          <div className="glass p-3 rounded text-sm" style={{borderLeft: '3px solid #22c55e', color: 'rgba(232, 234, 246, 0.8)'}}>
            ✅ Don't skip fundamentals - they're crucial
          </div>
          <div className="glass p-3 rounded text-sm" style={{borderLeft: '3px solid #22c55e', color: 'rgba(232, 234, 246, 0.8)'}}>
            ✅ Practice daily, even if just for 20 minutes
          </div>
          <div className="glass p-3 rounded text-sm" style={{borderLeft: '3px solid #22c55e', color: 'rgba(232, 234, 246, 0.8)'}}>
            ✅ Track your progress and adjust as needed
          </div>
          <div className="glass p-3 rounded text-sm" style={{borderLeft: '3px solid #22c55e', color: 'rgba(232, 234, 246, 0.8)'}}>
            ✅ Join communities for support and motivation
          </div>
        </div>
      </div>
    </div>
  );
};
export default StudyPlanner;
