import React, { useState } from 'react';
import enhancedAIService from '../services/enhancedAIService';
const StudyPlanner = () => {
  const [subject, setSubject] = useState('');
  const [duration, setDuration] = useState('4 weeks');
  const [level, setLevel] = useState('beginner');
  const [goals, setGoals] = useState('');
  const [studyPlan, setStudyPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const generatePlan = async () => {
    if (!subject || !goals) {
      alert('Please fill in subject and goals!');
      return;
    }
    setLoading(true);
    try {
      const plan = await enhancedAIService.createStudyPlan(subject, duration, level, goals);
      setStudyPlan(plan);
    } catch (error) {
      console.error('Error generating study plan:', error);
      alert('Failed to generate study plan. Please try again.');
    } finally {
      setLoading(false);
    }
  };
  const exportPlan = () => {
    if (!studyPlan) return;
    const planText = `
MY STUDY PLAN
=============
Subject: ${studyPlan.subject}
Duration: ${studyPlan.duration}
Level: ${studyPlan.level}
${studyPlan.plan}
Generated by AI Learning Tutor
${new Date().toLocaleDateString()}
    `;
    const blob = new Blob([planText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Study-Plan-${studyPlan.subject.replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };
  if (loading) {
    return (
      <div className="study-planner">
        <div className="loading-plan">
          <div className="spinner"></div>
          <p>Creating your personalized study plan...</p>
        </div>
      </div>
    );
  }
  if (!studyPlan) {
    return (
      <div className="study-planner">
        <div className="planner-setup">
          <h2>📅 Create Your Study Plan</h2>
          <p>Get a personalized, structured plan to master any subject</p>
          <div className="setup-form">
            <div className="form-group">
              <label>What do you want to learn?</label>
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                placeholder="e.g., Web Development, Data Science, Spanish"
              />
            </div>
            <div className="form-group">
              <label>How much time do you have?</label>
              <select value={duration} onChange={(e) => setDuration(e.target.value)}>
                <option value="2 weeks">2 Weeks (Crash Course)</option>
                <option value="4 weeks">4 Weeks (Standard)</option>
                <option value="8 weeks">8 Weeks (Comprehensive)</option>
                <option value="12 weeks">12 Weeks (In-Depth)</option>
                <option value="6 months">6 Months (Mastery)</option>
              </select>
            </div>
            <div className="form-group">
              <label>Current Level:</label>
              <div className="depth-selector">
                <button
                  className={`depth-btn ${level === 'beginner' ? 'active' : ''}`}
                  onClick={() => setLevel('beginner')}
                  type="button"
                >
                  🌱 Beginner
                </button>
                <button
                  className={`depth-btn ${level === 'intermediate' ? 'active' : ''}`}
                  onClick={() => setLevel('intermediate')}
                  type="button"
                >
                  📚 Intermediate
                </button>
                <button
                  className={`depth-btn ${level === 'advanced' ? 'active' : ''}`}
                  onClick={() => setLevel('advanced')}
                  type="button"
                >
                  ⭐ Advanced
                </button>
              </div>
            </div>
            <div className="form-group">
              <label>What are your learning goals?</label>
              <textarea
                value={goals}
                onChange={(e) => setGoals(e.target.value)}
                placeholder="e.g., Build a portfolio website, Get job-ready, Pass certification exam..."
                rows="4"
              />
            </div>
            <button className="generate-btn" onClick={generatePlan} type="button">
              Generate My Study Plan 🎯
            </button>
          </div>
          <div className="planner-features" style={{marginTop: '3rem', padding: '2rem', background: 'linear-gradient(135deg, rgba(37, 99, 235, 0.05), rgba(30, 64, 175, 0.03))', borderRadius: 'var(--radius-lg)', border: '2px solid var(--border-light)'}}>
            <h3 style={{textAlign: 'center', marginBottom: '1.5rem', color: 'var(--text-dark)', fontSize: '1.25rem', fontWeight: '700'}}>✨ Your Plan Includes:</h3>
            <div className="features-grid" style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.5rem'}}>
              <div className="feature-item" style={{textAlign: 'center', padding: '1.5rem', background: 'white', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-sm)', transition: 'all 0.3s ease'}}>
                <span className="icon" style={{fontSize: '2.5rem', display: 'block', marginBottom: '0.75rem'}}>📆</span>
                <p style={{color: 'var(--text-medium)', fontWeight: '600', fontSize: '0.95rem'}}>Week-by-week breakdown</p>
              </div>
              <div className="feature-item" style={{textAlign: 'center', padding: '1.5rem', background: 'white', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-sm)', transition: 'all 0.3s ease'}}>
                <span className="icon" style={{fontSize: '2.5rem', display: 'block', marginBottom: '0.75rem'}}>⏰</span>
                <p style={{color: 'var(--text-medium)', fontWeight: '600', fontSize: '0.95rem'}}>Daily time allocation</p>
              </div>
              <div className="feature-item" style={{textAlign: 'center', padding: '1.5rem', background: 'white', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-sm)', transition: 'all 0.3s ease'}}>
                <span className="icon" style={{fontSize: '2.5rem', display: 'block', marginBottom: '0.75rem'}}>📚</span>
                <p style={{color: 'var(--text-medium)', fontWeight: '600', fontSize: '0.95rem'}}>Specific topics to cover</p>
              </div>
              <div className="feature-item" style={{textAlign: 'center', padding: '1.5rem', background: 'white', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-sm)', transition: 'all 0.3s ease'}}>
                <span className="icon" style={{fontSize: '2.5rem', display: 'block', marginBottom: '0.75rem'}}>🎯</span>
                <p style={{color: 'var(--text-medium)', fontWeight: '600', fontSize: '0.95rem'}}>Milestones & checkpoints</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
  return (
    <div className="study-planner">
      <div className="study-plan-view">
        <div className="plan-header">
          <h2 className="plan-title">📚 Your Personalized Study Plan</h2>
          <div className="plan-meta">
            <span className="meta-item">📖 {studyPlan.subject}</span>
            <span className="meta-item">⏱️ {studyPlan.duration}</span>
            <span className="meta-item">📊 {studyPlan.level}</span>
          </div>
        </div>
        <div className="milestones-list" style={{listStyle: 'none', padding: 0}}>
          {studyPlan.plan.split('\n\n').filter(section => section.trim()).map((section, index) => {
            const lines = section.split('\n');
            const title = lines[0].replace(/\*\*/g, '').trim();
            const content = lines.slice(1).join('\n');
            return (
              <div key={index} className="milestone-item">
                <div className="milestone-header">
                  <h3 className="milestone-title">{title}</h3>
                  <span className="milestone-duration">Week {index + 1}</span>
                </div>
                <div className="milestone-content">
                  {content.split('\n').map((line, i) => {
                    if (line.trim().startsWith('•') || line.trim().startsWith('✓') || line.trim().startsWith('→')) {
                      return <p key={i} style={{marginLeft: '1rem'}}>• {line.substring(1).trim()}</p>;
                    } else if (line.trim()) {
                      return <p key={i}>{line}</p>;
                    }
                    return null;
                  })}
                </div>
              </div>
            );
          })}
        </div>
        <div className="plan-actions" style={{display: 'flex', gap: '1rem', marginTop: '2.5rem', flexWrap: 'wrap'}}>
          <button 
            className="new-plan-btn"
            onClick={() => setStudyPlan(null)}
            type="button"
            style={{flex: 1, minWidth: '200px'}}
          >
            📝 Create New Plan
          </button>
          <button 
            className="generate-btn" 
            onClick={exportPlan}
            type="button"
            style={{flex: 1, minWidth: '200px', background: 'linear-gradient(135deg, var(--success-color), #059669)'}}
          >
            📥 Export Plan
          </button>
        </div>
        <div className="plan-tips" style={{marginTop: '3rem', padding: '2rem', background: 'linear-gradient(135deg, rgba(16, 185, 129, 0.05), rgba(5, 150, 105, 0.03))', borderRadius: 'var(--radius-lg)', border: '2px solid rgba(16, 185, 129, 0.2)'}}>
          <h3 style={{color: 'var(--text-dark)', fontSize: '1.25rem', marginBottom: '1.25rem', fontWeight: '700'}}>💡 Tips for Success</h3>
          <ul style={{listStyle: 'none', padding: 0, display: 'grid', gap: '0.75rem'}}>
            <li style={{padding: '0.75rem 1rem', background: 'white', borderRadius: 'var(--radius-md)', borderLeft: '4px solid var(--success-color)', color: 'var(--text-medium)', fontSize: '0.95rem'}}>✅ Stick to the schedule - consistency is key</li>
            <li style={{padding: '0.75rem 1rem', background: 'white', borderRadius: 'var(--radius-md)', borderLeft: '4px solid var(--success-color)', color: 'var(--text-medium)', fontSize: '0.95rem'}}>✅ Don't skip fundamentals - they're crucial</li>
            <li style={{padding: '0.75rem 1rem', background: 'white', borderRadius: 'var(--radius-md)', borderLeft: '4px solid var(--success-color)', color: 'var(--text-medium)', fontSize: '0.95rem'}}>✅ Practice daily, even if just for 20 minutes</li>
            <li style={{padding: '0.75rem 1rem', background: 'white', borderRadius: 'var(--radius-md)', borderLeft: '4px solid var(--success-color)', color: 'var(--text-medium)', fontSize: '0.95rem'}}>✅ Track your progress and adjust as needed</li>
            <li style={{padding: '0.75rem 1rem', background: 'white', borderRadius: 'var(--radius-md)', borderLeft: '4px solid var(--success-color)', color: 'var(--text-medium)', fontSize: '0.95rem'}}>✅ Join communities for support and motivation</li>
          </ul>
        </div>
      </div>
    </div>
  );
};
export default StudyPlanner;
